// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chess.proto

#include "chess.pb.h"
#include "chess.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace fdqms {

static const char* SatrancService_method_names[] = {
  "/fdqms.SatrancService/Login",
  "/fdqms.SatrancService/Register",
  "/fdqms.SatrancService/CreateGame",
  "/fdqms.SatrancService/SearchGame",
  "/fdqms.SatrancService/LeaveGame",
  "/fdqms.SatrancService/SendDraw",
  "/fdqms.SatrancService/AccetpDraw",
  "/fdqms.SatrancService/DeclineDraw",
  "/fdqms.SatrancService/Connect",
  "/fdqms.SatrancService/Move",
  "/fdqms.SatrancService/Promotion",
};

std::unique_ptr< SatrancService::Stub> SatrancService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SatrancService::Stub> stub(new SatrancService::Stub(channel, options));
  return stub;
}

SatrancService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(SatrancService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Register_(SatrancService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateGame_(SatrancService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchGame_(SatrancService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LeaveGame_(SatrancService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendDraw_(SatrancService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AccetpDraw_(SatrancService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeclineDraw_(SatrancService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Connect_(SatrancService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Move_(SatrancService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Promotion_(SatrancService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SatrancService::Stub::Login(::grpc::ClientContext* context, const ::fdqms::LoginRequest& request, ::fdqms::User* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::LoginRequest, ::fdqms::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void SatrancService::Stub::async::Login(::grpc::ClientContext* context, const ::fdqms::LoginRequest* request, ::fdqms::User* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::LoginRequest, ::fdqms::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::Login(::grpc::ClientContext* context, const ::fdqms::LoginRequest* request, ::fdqms::User* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::User>* SatrancService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::fdqms::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::User, ::fdqms::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::User>* SatrancService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::fdqms::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::Register(::grpc::ClientContext* context, const ::fdqms::RegisterRequest& request, ::fdqms::User* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::RegisterRequest, ::fdqms::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Register_, context, request, response);
}

void SatrancService::Stub::async::Register(::grpc::ClientContext* context, const ::fdqms::RegisterRequest* request, ::fdqms::User* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::RegisterRequest, ::fdqms::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::Register(::grpc::ClientContext* context, const ::fdqms::RegisterRequest* request, ::fdqms::User* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::User>* SatrancService::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::fdqms::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::User, ::fdqms::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Register_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::User>* SatrancService::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::fdqms::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::CreateGame(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::fdqms::GameID* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateGame_, context, request, response);
}

void SatrancService::Stub::async::CreateGame(::grpc::ClientContext* context, const ::fdqms::Empty* request, ::fdqms::GameID* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateGame_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::CreateGame(::grpc::ClientContext* context, const ::fdqms::Empty* request, ::fdqms::GameID* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::GameID>* SatrancService::Stub::PrepareAsyncCreateGameRaw(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::GameID>* SatrancService::Stub::AsyncCreateGameRaw(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::SearchGame(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::fdqms::GameID* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SearchGame_, context, request, response);
}

void SatrancService::Stub::async::SearchGame(::grpc::ClientContext* context, const ::fdqms::Empty* request, ::fdqms::GameID* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchGame_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::SearchGame(::grpc::ClientContext* context, const ::fdqms::Empty* request, ::fdqms::GameID* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::GameID>* SatrancService::Stub::PrepareAsyncSearchGameRaw(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SearchGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::GameID>* SatrancService::Stub::AsyncSearchGameRaw(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSearchGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::LeaveGame(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::fdqms::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LeaveGame_, context, request, response);
}

void SatrancService::Stub::async::LeaveGame(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveGame_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::LeaveGame(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::PrepareAsyncLeaveGameRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LeaveGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::AsyncLeaveGameRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLeaveGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::SendDraw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::fdqms::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDraw_, context, request, response);
}

void SatrancService::Stub::async::SendDraw(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDraw_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::SendDraw(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDraw_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::PrepareAsyncSendDrawRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDraw_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::AsyncSendDrawRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDrawRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::AccetpDraw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::fdqms::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AccetpDraw_, context, request, response);
}

void SatrancService::Stub::async::AccetpDraw(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AccetpDraw_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::AccetpDraw(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AccetpDraw_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::PrepareAsyncAccetpDrawRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AccetpDraw_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::AsyncAccetpDrawRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAccetpDrawRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::DeclineDraw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::fdqms::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeclineDraw_, context, request, response);
}

void SatrancService::Stub::async::DeclineDraw(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeclineDraw_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::DeclineDraw(::grpc::ClientContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeclineDraw_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::PrepareAsyncDeclineDrawRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeclineDraw_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::AsyncDeclineDrawRaw(::grpc::ClientContext* context, const ::fdqms::GameID& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeclineDrawRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::fdqms::Position>* SatrancService::Stub::ConnectRaw(::grpc::ClientContext* context, const ::fdqms::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::fdqms::Position>::Create(channel_.get(), rpcmethod_Connect_, context, request);
}

void SatrancService::Stub::async::Connect(::grpc::ClientContext* context, const ::fdqms::Empty* request, ::grpc::ClientReadReactor< ::fdqms::Position>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::fdqms::Position>::Create(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::fdqms::Position>* SatrancService::Stub::AsyncConnectRaw(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::fdqms::Position>::Create(channel_.get(), cq, rpcmethod_Connect_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::fdqms::Position>* SatrancService::Stub::PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::fdqms::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::fdqms::Position>::Create(channel_.get(), cq, rpcmethod_Connect_, context, request, false, nullptr);
}

::grpc::Status SatrancService::Stub::Move(::grpc::ClientContext* context, const ::fdqms::Position& request, ::fdqms::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::Position, ::fdqms::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Move_, context, request, response);
}

void SatrancService::Stub::async::Move(::grpc::ClientContext* context, const ::fdqms::Position* request, ::fdqms::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::Position, ::fdqms::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Move_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::Move(::grpc::ClientContext* context, const ::fdqms::Position* request, ::fdqms::Result* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Move_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Result>* SatrancService::Stub::PrepareAsyncMoveRaw(::grpc::ClientContext* context, const ::fdqms::Position& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::Result, ::fdqms::Position, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Move_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Result>* SatrancService::Stub::AsyncMoveRaw(::grpc::ClientContext* context, const ::fdqms::Position& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMoveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SatrancService::Stub::Promotion(::grpc::ClientContext* context, const ::fdqms::Position& request, ::fdqms::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdqms::Position, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Promotion_, context, request, response);
}

void SatrancService::Stub::async::Promotion(::grpc::ClientContext* context, const ::fdqms::Position* request, ::fdqms::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdqms::Position, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Promotion_, context, request, response, std::move(f));
}

void SatrancService::Stub::async::Promotion(::grpc::ClientContext* context, const ::fdqms::Position* request, ::fdqms::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Promotion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::PrepareAsyncPromotionRaw(::grpc::ClientContext* context, const ::fdqms::Position& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdqms::Empty, ::fdqms::Position, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Promotion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdqms::Empty>* SatrancService::Stub::AsyncPromotionRaw(::grpc::ClientContext* context, const ::fdqms::Position& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPromotionRaw(context, request, cq);
  result->StartCall();
  return result;
}

SatrancService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::LoginRequest, ::fdqms::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::LoginRequest* req,
             ::fdqms::User* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::RegisterRequest, ::fdqms::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::RegisterRequest* req,
             ::fdqms::User* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::Empty* req,
             ::fdqms::GameID* resp) {
               return service->CreateGame(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::Empty, ::fdqms::GameID, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::Empty* req,
             ::fdqms::GameID* resp) {
               return service->SearchGame(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::GameID* req,
             ::fdqms::Empty* resp) {
               return service->LeaveGame(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::GameID* req,
             ::fdqms::Empty* resp) {
               return service->SendDraw(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::GameID* req,
             ::fdqms::Empty* resp) {
               return service->AccetpDraw(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::GameID, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::GameID* req,
             ::fdqms::Empty* resp) {
               return service->DeclineDraw(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SatrancService::Service, ::fdqms::Empty, ::fdqms::Position>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::Empty* req,
             ::grpc::ServerWriter<::fdqms::Position>* writer) {
               return service->Connect(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::Position, ::fdqms::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::Position* req,
             ::fdqms::Result* resp) {
               return service->Move(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatrancService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatrancService::Service, ::fdqms::Position, ::fdqms::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatrancService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdqms::Position* req,
             ::fdqms::Empty* resp) {
               return service->Promotion(ctx, req, resp);
             }, this)));
}

SatrancService::Service::~Service() {
}

::grpc::Status SatrancService::Service::Login(::grpc::ServerContext* context, const ::fdqms::LoginRequest* request, ::fdqms::User* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::Register(::grpc::ServerContext* context, const ::fdqms::RegisterRequest* request, ::fdqms::User* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::CreateGame(::grpc::ServerContext* context, const ::fdqms::Empty* request, ::fdqms::GameID* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::SearchGame(::grpc::ServerContext* context, const ::fdqms::Empty* request, ::fdqms::GameID* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::LeaveGame(::grpc::ServerContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::SendDraw(::grpc::ServerContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::AccetpDraw(::grpc::ServerContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::DeclineDraw(::grpc::ServerContext* context, const ::fdqms::GameID* request, ::fdqms::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::Connect(::grpc::ServerContext* context, const ::fdqms::Empty* request, ::grpc::ServerWriter< ::fdqms::Position>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::Move(::grpc::ServerContext* context, const ::fdqms::Position* request, ::fdqms::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SatrancService::Service::Promotion(::grpc::ServerContext* context, const ::fdqms::Position* request, ::fdqms::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fdqms

